package com.example.localization

enum class AppLanguage(val code: String, val displayName: String, val shortCode: String) {
    ENGLISH("en", "English", "EN"),
    ARABIC("ar", "العربية", "AR"),
    FRENCH("fr", "Français", "FR")
}

data class AppStrings(
    val appName: String,
    val appSubtitle: String,
    val navHome: String,
    val navLibrary: String,
    val navEqualizer: String,
    val navAiFinder: String,
    val navAbout: String,
    val nowPlaying: String,
    val recommendedForYou: String,
    val shuffleAll: String,
    val favorites: String,
    val recentlyPlayed: String,
    val exploreGenres: String,
    val allTracks: String,
    val viewAll: String,
    val searchPlaceholder: String,
    val tabSongs: String,
    val tabFavorites: String,
    val tabPlaylists: String,
    val tabArtists: String,
    val tabAlbums: String,
    val tabGenres: String,
    val createPlaylist: String,
    val playlistName: String,
    val create: String,
    val cancel: String,
    val close: String,
    val addToPlaylist: String,
    val playNow: String,
    val removeFromPlaylist: String,
    val noSongsInTab: String,
    val noPlaylistsYet: String,
    val createPlaylistPrompt: String,
    val eqTitle: String,
    val eqSubtitle: String,
    val masterSwitch: String,
    val spectrumAnalyzer: String,
    val bassBoost: String,
    val surround3d: String,
    val presets: String,
    val dspEngine: String,
    val dspSpecs: String,
    val sleepTimer: String,
    val sleepTimerActive: String,
    val sleepTimerPrompt: String,
    val setTimer: String,
    val cancelTimer: String,
    val speed: String,
    val queue: String,
    val coverArt: String,
    val lyrics: String,
    val noLyrics: String,
    val aiFinderTitle: String,
    val aiFinderSubtitle: String,
    val aiListening: String,
    val tapToIdentify: String,
    val searchByLyricsPrompt: String,
    val searchAiBtn: String,
    val songIdentified: String,
    val confidence: String,
    val artist: String,
    val album: String,
    val genre: String,
    val year: String,
    val trivia: String,
    val playInApp: String,
    val searchInLibrary: String,
    val devInfo: String,
    val devEmail: String,
    val sendEmail: String,
    val copyEmail: String,
    val gitRepo: String,
    val openRepo: String,
    val shareApp: String,
    val specsTitle: String,
    val permissionBannerTitle: String,
    val permissionBannerDesc: String,
    val grantPermission: String,
    val language: String,
    val permissionGranted: String,
    val addMusic: String,
    val scanStorage: String,
    val noMusicFound: String,
    val noMusicFoundPrompt: String
)

object Localization {

    val english = AppStrings(
        appName = "AuraWave",
        appSubtitle = "Luxurious High-Fidelity Music Experience",
        navHome = "Home",
        navLibrary = "Library",
        navEqualizer = "Equalizer",
        navAiFinder = "AI Song Finder",
        navAbout = "About",
        nowPlaying = "Now Playing",
        recommendedForYou = "Your Audio Files",
        shuffleAll = "Shuffle All",
        favorites = "Favorites",
        recentlyPlayed = "Recently Played",
        exploreGenres = "Explore by Genre",
        allTracks = "All My Tracks",
        viewAll = "View All",
        searchPlaceholder = "Search your songs, artists, albums...",
        tabSongs = "Songs",
        tabFavorites = "Favorites",
        tabPlaylists = "Playlists",
        tabArtists = "Artists",
        tabAlbums = "Albums",
        tabGenres = "Genres",
        createPlaylist = "Create New Playlist",
        playlistName = "Playlist Name",
        create = "Create",
        cancel = "Cancel",
        close = "Close",
        addToPlaylist = "Add to Playlist",
        playNow = "Play Now",
        removeFromPlaylist = "Remove from Playlist",
        noSongsInTab = "No songs found in this section",
        noPlaylistsYet = "No playlists created yet",
        createPlaylistPrompt = "Tap below to create your first custom playlist",
        eqTitle = "Pro 5-Band Equalizer",
        eqSubtitle = "Precision frequency tuning & sound enhancement",
        masterSwitch = "Equalizer Power",
        spectrumAnalyzer = "Live Real-Time Spectrum Analyzer",
        bassBoost = "Bass Boost",
        surround3d = "3D Surround",
        presets = "Equalizer Presets",
        dspEngine = "32-Bit Float DSP Audio Engine",
        dspSpecs = "44.1 kHz • Ultra-low latency • Studio acoustic filters",
        sleepTimer = "Sleep Timer",
        sleepTimerActive = "Active: %d min remaining",
        sleepTimerPrompt = "Select duration to stop music playback automatically:",
        setTimer = "Set Timer",
        cancelTimer = "Cancel Timer",
        speed = "Speed",
        queue = "Up Next Queue",
        coverArt = "Cover Art",
        lyrics = "Lyrics",
        noLyrics = "Lyrics not available for this track",
        aiFinderTitle = "AI Music Identifier",
        aiFinderSubtitle = "Listen, hum or describe any melody to identify it with Gemini AI",
        aiListening = "Listening & analyzing melody...",
        tapToIdentify = "Tap to Listen & Identify",
        searchByLyricsPrompt = "Or type lyrics, mood, or melody description:",
        searchAiBtn = "Identify with AI",
        songIdentified = "Song Identified Successfully!",
        confidence = "Confidence",
        artist = "Artist",
        album = "Album",
        genre = "Genre",
        year = "Year",
        trivia = "Story & Trivia",
        playInApp = "Play in AuraWave",
        searchInLibrary = "Find in Library",
        devInfo = "Developer & Contact",
        devEmail = "ahmedbecetti41@gmail.com",
        sendEmail = "Email Developer",
        copyEmail = "Copy Email",
        gitRepo = "GitHub Repository & Downloads",
        openRepo = "Open GitHub Repo",
        shareApp = "Share App",
        specsTitle = "Technical Specifications",
        permissionBannerTitle = "Device Files & Audio Access",
        permissionBannerDesc = "Grant permission to scan and play all audio tracks from your phone storage",
        grantPermission = "Grant Permission",
        language = "Language",
        permissionGranted = "Permission granted! Scanned audio tracks.",
        addMusic = "Add Audio Files",
        scanStorage = "Scan Phone Storage",
        noMusicFound = "No Music Files Found on Device",
        noMusicFoundPrompt = "Tap below to select your own MP3/FLAC songs from your files or scan your device storage"
    )

    val arabic = AppStrings(
        appName = "AuraWave",
        appSubtitle = "تجربة موسيقية فاخرة عالية الدقة",
        navHome = "الرئيسية",
        navLibrary = "المكتبة",
        navEqualizer = "المعادل",
        navAiFinder = "ذكاء اصطناعي",
        navAbout = "حول التطبيق",
        nowPlaying = "قيد التشغيل الآن",
        recommendedForYou = "ملفاتك الصوتية",
        shuffleAll = "خلط الكل",
        favorites = "المفضلة",
        recentlyPlayed = "تم تشغيلها مؤخراً",
        exploreGenres = "استكشف حسب التصنيف",
        allTracks = "أغاني جهازي",
        viewAll = "عرض الكل",
        searchPlaceholder = "بحث في أغانيك، فنان، ألبوم...",
        tabSongs = "الأغاني",
        tabFavorites = "المفضلة",
        tabPlaylists = "قوائم التشغيل",
        tabArtists = "الفنانون",
        tabAlbums = "الألبومات",
        tabGenres = "الأنواع",
        createPlaylist = "إنشاء قائمة تشغيل جديدة",
        playlistName = "اسم القائمة الموسيقية",
        create = "إنشاء",
        cancel = "إلغاء",
        close = "إغلاق",
        addToPlaylist = "إضافة إلى قائمة تشغيل",
        playNow = "تشغيل الآن",
        removeFromPlaylist = "إزالة من القائمة",
        noSongsInTab = "لا توجد أغانٍ متوفرة في هذا القسم",
        noPlaylistsYet = "لا توجد قوائم تشغيل حتى الآن",
        createPlaylistPrompt = "اضغط أدناه لإنشاء أول قائمة تشغيل مخصصة",
        eqTitle = "معادل الصوت الاحترافي",
        eqSubtitle = "تحكم كامل في ترددات الصوت والمؤثرات",
        masterSwitch = "تفعيل المعادل",
        spectrumAnalyzer = "محلل الترددات الطيفي المباشر",
        bassBoost = "تضخيم الباس",
        surround3d = "صوت محيطي 3D",
        presets = "الإعدادات المسبقة",
        dspEngine = "معالجة صوتية رقمية 32-Bit Float",
        dspSpecs = "44.1 kHz • استجابة فورية فائقة • فلاتر استوديو نقية",
        sleepTimer = "مؤقت النوم",
        sleepTimerActive = "المؤقت نشط: يتبقى %d دقيقة",
        sleepTimerPrompt = "اختر المدة التي تريد إيقاف تشغيل الموسيقى بعدها تلقائياً:",
        setTimer = "تفعيل المؤقت",
        cancelTimer = "إلغاء المؤقت",
        speed = "السرعة",
        queue = "قائمة الانتظار",
        coverArt = "غلاف الألبوم",
        lyrics = "الكلمات",
        noLyrics = "كلمات الأغنية غير متوفرة لهذا المقطع",
        aiFinderTitle = "معرّف الأغاني بالذكاء الاصطناعي",
        aiFinderSubtitle = "استمع أو دندن أو صف أي أغنية للتعرف عليها فوراً عبر الذكاء الاصطناعي",
        aiListening = "جاري الاستماع وتحليل النغمات الصوتية...",
        tapToIdentify = "اضغط للاستماع والتعرف على الأغنية",
        searchByLyricsPrompt = "أو اكتب كلمات الأغنية أو وصف اللحن للبحث:",
        searchAiBtn = "التعرف بالذكاء الاصطناعي",
        songIdentified = "تم التعرف على الأغنية بنجاح!",
        confidence = "دقة التعرف",
        artist = "الفنان",
        album = "الألبوم",
        genre = "النوع",
        year = "السنة",
        trivia = "قصة ونبذة عن الأغنية",
        playInApp = "تشغيل في AuraWave",
        searchInLibrary = "بحث في مكتبة الهاتف",
        devInfo = "المطور وبيانات التواصل",
        devEmail = "ahmedbecetti41@gmail.com",
        sendEmail = "مراسلة المطور عبر البريد",
        copyEmail = "نسخ البريد",
        gitRepo = "مستودع GitHub والتحميل",
        openRepo = "فتح مستودع GitHub",
        shareApp = "مشاركة التطبيق",
        specsTitle = "مواصفات ومزايا التطبيق الفنية",
        permissionBannerTitle = "إذن الوصول للملفات الصوتية",
        permissionBannerDesc = "امنح الإذن لقراءة وتشغيل جميع الملفات الصوتية المخزنة على هاتفك",
        grantPermission = "منح الإذن الآن",
        language = "اللغة",
        permissionGranted = "تم منح الإذن بنجاح! تم مسح مكتبة الصوتيات.",
        addMusic = "إضافة ملفات صوتية من الهاتف",
        scanStorage = "فحص ذاكرة الهاتف",
        noMusicFound = "لا توجد ملفات صوتية بعد في جهازك",
        noMusicFoundPrompt = "اضغط أدناه لاختيار أغانيك الخاصة من ملفات الهاتف أو مسح الذاكرة"
    )

    val french = AppStrings(
        appName = "AuraWave",
        appSubtitle = "Expérience Musicale Haute Fidélité Luxueuse",
        navHome = "Accueil",
        navLibrary = "Bibliothèque",
        navEqualizer = "Égaliseur",
        navAiFinder = "Finder IA",
        navAbout = "À propos",
        nowPlaying = "En lecture",
        recommendedForYou = "Vos fichiers audio",
        shuffleAll = "Lecture aléatoire",
        favorites = "Favoris",
        recentlyPlayed = "Récemment écoutés",
        exploreGenres = "Explorer par genre",
        allTracks = "Tous mes titres",
        viewAll = "Voir tout",
        searchPlaceholder = "Rechercher parmi vos titres, artistes...",
        tabSongs = "Titres",
        tabFavorites = "Favoris",
        tabPlaylists = "Playlists",
        tabArtists = "Artistes",
        tabAlbums = "Albums",
        tabGenres = "Genres",
        createPlaylist = "Créer une playlist",
        playlistName = "Nom de la playlist",
        create = "Créer",
        cancel = "Annuler",
        close = "Fermer",
        addToPlaylist = "Ajouter à la playlist",
        playNow = "Écouter maintenant",
        removeFromPlaylist = "Retirer de la playlist",
        noSongsInTab = "Aucun titre trouvé dans cette section",
        noPlaylistsYet = "Aucune playlist pour le moment",
        createPlaylistPrompt = "Appuyez ci-dessous pour créer votre première playlist",
        eqTitle = "Égaliseur Pro 5 Bandes",
        eqSubtitle = "Réglage acoustique de haute précision",
        masterSwitch = "Alimentation Égaliseur",
        spectrumAnalyzer = "Analyseur de spectre en direct",
        bassBoost = "Amplification des basses",
        surround3d = "Son Surround 3D",
        presets = "Préréglages d'égalisation",
        dspEngine = "Moteur audio DSP 32-Bit Float",
        dspSpecs = "44.1 kHz • Latence ultra-faible • Filtres acoustiques studio",
        sleepTimer = "Minuterie de veille",
        sleepTimerActive = "Actif : %d min restantes",
        sleepTimerPrompt = "Choisissez la durée avant l'arrêt automatique de la musique :",
        setTimer = "Activer la minuterie",
        cancelTimer = "Désactiver",
        speed = "Vitesse",
        queue = "File d'attente",
        coverArt = "Pochette",
        lyrics = "Paroles",
        noLyrics = "Paroles non disponibles pour ce titre",
        aiFinderTitle = "Reconnaissance Musicale IA",
        aiFinderSubtitle = "Écoutez, fredonnez ou décrivez un morceau pour l'identifier avec l'IA Gemini",
        aiListening = "Écoute et analyse acoustique en cours...",
        tapToIdentify = "Appuyer pour identifier",
        searchByLyricsPrompt = "Ou saisissez des paroles ou une description :",
        searchAiBtn = "Identifier avec l'IA",
        songIdentified = "Morceau identifié avec succès !",
        confidence = "Précision",
        artist = "Artiste",
        album = "Album",
        genre = "Genre",
        year = "Année",
        trivia = "Histoire & Anecdote",
        playInApp = "Écouter dans AuraWave",
        searchInLibrary = "Trouver dans la bibliothèque",
        devInfo = "Développeur & Contact",
        devEmail = "ahmedbecetti41@gmail.com",
        sendEmail = "Envoyer un e-mail",
        copyEmail = "Copier l'e-mail",
        gitRepo = "Dépôt GitHub & Téléchargements",
        openRepo = "Ouvrir le dépôt GitHub",
        shareApp = "Partager l'application",
        specsTitle = "Spécifications techniques",
        permissionBannerTitle = "Accès aux fichiers audio",
        permissionBannerDesc = "Autorisez l'application à lire et jouer les musiques de votre appareil",
        grantPermission = "Accorder l'autorisation",
        language = "Langue",
        permissionGranted = "Autorisation accordée ! Fichiers audio synchronisés.",
        addMusic = "Ajouter des musiques",
        scanStorage = "Scanner le stockage",
        noMusicFound = "Aucune musique trouvée sur l'appareil",
        noMusicFoundPrompt = "Appuyez ci-dessous pour importer vos fichiers audio (MP3/FLAC) ou scanner l'appareil"
    )

    fun get(language: AppLanguage): AppStrings = when (language) {
        AppLanguage.ENGLISH -> english
        AppLanguage.ARABIC -> arabic
        AppLanguage.FRENCH -> french
    }
}
